Add: check permissions for session key owners in validation
AA-Contract/account-abstraction pull request #6
Opened 2023-06-08 11:04 UTC by sm-stack

2023-06-08 12:11 UTC, Sangyeup commented on contracts/test/TestExpiryAccount.sol
> +        if (getSelector(calldataCopy) != "0xdade6037") {
Please also add executeBatch function here!

2023-06-08 12:11 UTC, Sangyeup commented on contracts/test/TestExpiryAccount.sol
> +        if (getSelector(calldataCopy) != "0xdade6037") {
Please change calldataCopy to userOp.calldata

2023-06-08 12:11 UTC, Sangyeup commented on contracts/test/TestExpiryAccount.sol
> +                        if (permission.whitelistMethods[j] == getSelector(userOp.calldata)) {
userOp.calldata -> func

2023-06-08 12:11 UTC, Sangyeup commented on contracts/test/TestExpiryAccount.sol
> +        for(uint i; i < permissionLength; i++) {
Should consider changed addTemporaryOwner function

2023-06-15 05:35 UTC, sm-stack commented
Fixed all above checks
Resolved type collision at getSelector / addTemporaryOwner
Fixed invalid sigFailed flag at _validateSessionKey

2023-06-15 07:31 UTC, Sangyeup requested changes

2023-06-15 07:31 UTC, Sangyeup commented on contracts/test/TestExpiryAccount.sol
> +    function decodeSingle(bytes calldata _data) public pure returns (address dest, uint256 value, bytes memory func){
Please change function name to _decodeSingle!

2023-06-15 07:31 UTC, Sangyeup commented on contracts/test/TestExpiryAccount.sol
> +    function decodeBatch(bytes calldata _data) public pure returns (address[] memory dest, bytes[] memory func){
Please change function name to _decodeBatch!

2023-06-15 07:31 UTC, Sangyeup commented on contracts/test/TestExpiryAccount.sol
> +    function _validateSessionKeyBatch(bytes calldata userOpCallData, address signer, uint48 _until, uint48 _after)
Will be better if we can integrate _validateSessionKeySingle and _validateSessionKeyBatch to one function. Below is what I changed! You should also change _validateSignature and _decodeSingle function to adjust.

`
function _validateSessionKey(
    bytes calldata userOpCallData, address signer, uint48 _until, uint48 _after, bytes4 userOpSelector
)

    internal view returns (uint256 validationData) {

	if (userOpSelector == FUNCTION_EXECUTE) {
	    (address[] memory dest, , bytes[] memory func) = decodeSingle(userOpCallData); 	
	} else {
	    (address[] memory dest, bytes[] memory func) = decodeBatch(userOpCallData);
	}

        PermissionStorage storage permissionStorage = permissionMap[signer];

        bool sigFailed = true;

        uint256 length = dest.length;
        for (uint256 i = 0; i < length; i++) {
            if (permissionStorage.whitelistDestinationMap[dest[i]]) {
                if (permissionStorage.whitelistMethodsMap[dest[i]][this.getSelector(func[i])]) {
                    sigFailed = false;
                    break;
                    // Token Approval??
                }
            }
        }
        return _packValidationData(sigFailed, _until, _after);`

2023-06-19 09:33 UTC, Sangyeup commented
@sm-stack LGTM!

2023-06-19 09:33 UTC, merged